#pragma once
#include "conditions/argindex.hpp"
#include "conditions/between.hpp"
#include "conditions/difference.hpp"
#include "conditions/equals.hpp"
#include "conditions/field.hpp"
#include "conditions/minmax.hpp"
#include "conditions/oddeven.hpp"
#include "conditions/property.hpp"